#ifndef CONFIGURATOR_H
#define CONFIGURATOR_H

#include <string>
#include <Commons.h>
#include <mutex>

class ScreenLedConfigurator
{
public:
    ScreenLedConfigurator();
    void updateCurrentConfig(ScreenCapConfig newConf, bool save);
    ScreenCapConfig getCurrentConfig();

private:
    bool loadConfigs();
    bool createConfigFile();

    std::string m_configPath = "screenLedConfig.json"; //using runtimefolder should be fine for now since if this file does not exist, it gets generated by screenCaptureWorker during its initialization
    ScreenCapConfig m_conf;
    std::mutex m_conf_mutex;
};

#endif // CONFIGURATOR_H
