#ifndef MAINGUI_H
#define MAINGUI_H


#include <QMainWindow>
#include <QHBoxLayout>
#include <QThread>

#include "consts.h"
#if defined(WIN32)
#include "ScreenCapWindows.h"
#else
#include "ScreenCapLinux.h"
#endif

#include "receiverrunnerssh.h"
#include "receiverconsole.h"

namespace Ui {
class MainGUI;
}

class MainGUI : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainGUI(QWidget *parent = nullptr);
    ~MainGUI();

private slots:
    void on_actionExit_triggered();

    void on_mainGUIAlgoSelect_currentIndexChanged(int index);

    void on_mainGUIAlgoSelect_currentTextChanged(const QString &arg1);

    void on_actionAbout_triggered();

    void on_actionConfiguration_triggered();

    void on_startButt_clicked();

    void on_startReceiversButt_clicked();

    void on_actionReceiver_console_triggered();

private:
    Ui::MainGUI *ui;

    // functions
    void populateAlgoSelect();
    void populateReceiverStatusRows();
    void onExitActions();
    bool startReceivers();
    bool stopReceivers();

    // vars
    QVector<QHBoxLayout*> m_receiverStatusRows;
    runStatus m_libRunStatus = runStatus::IDLE;
    ReceiverRunnerSSH* m_rcvRunner = nullptr;
    QThread* m_rcvRunnerThread = nullptr;
    static constexpr int m_maxRcvRunnerLines = 100;
    std::vector<QString> m_rcvRunnerOutput;
    bool m_receiversRunning = false;
    bool m_receiverConsoleOpen = false;
    bool m_receiverConsoleInitialFillOngoing = false; // to prevent live output from being appended when console is just opened
    ReceiverConsole *m_receiverConsole = nullptr;

    // screenledlib things
    QThread* m_screenLibTh = new QThread;
    std::string m_gConfPath = "screenLedConfig.json"; //using runtimefolder should be fine for now since if this file does not exist, it gets generated by screenCaptureWorker during its initialization
#if defined(WIN32)
    screenCaptureWorkerWindows* m_screenCapWorker = nullptr;
#else
    screenCaptureWorkerLinux* m_screenCapWorker = nullptr;
#endif
};

#endif // MAINGUI_H
