#ifndef SCREENLEDGUI_H
#define SCREENLEDGUI_H

#include <QMainWindow>
#include <QThread>
#include <QTimer>
#include "qlineedit.h"

#include "consts.h"
#if defined(WIN32)
#include "ScreenCapWindows.h"
#else
#include "ScreenCapLinux.h"
#endif

#include "receiverrunner.h"
#include "advancedsettings.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class ScreenLedGUI;
}
QT_END_NAMESPACE

class ScreenLedGUI : public QMainWindow
{
    Q_OBJECT

public:
    ScreenLedGUI(QWidget *parent = nullptr);
    ~ScreenLedGUI();

    // allow advanced settings window to access this object's screencapworker's configuration
    ScreenCapConfig getScreenCapWorkerConf() {
        if (!m_screenCapWorker) {
            qWarning() << "getScreenCapWorkerConf() NO m_screenCapWorker. Returning default conf";
            return ScreenCapConfig();
        }
        return m_screenCapWorker->getCurrentConfig();
    }
    bool setScreenCapWorkerConf(ScreenCapConfig conf) {
        if (!m_screenCapWorker) {
            qWarning() << "No m_screenCapWorker";
            return false;
        }
        m_screenCapWorker->updateCurrentConfig(conf);
        return true;
    }

private slots:
    void on_startButton_clicked();

    void on_saveConfig_clicked();

    void on_algoSelectVal_currentTextChanged(const QString &arg1);

    void on_addAnotherClientButt_clicked();

    void on_startRcvsButton_clicked();

    void on_selectAutoRunScriptFile_clicked();

    void on_advancedSettings_clicked();

private:
    //functions
    int fillConfigForm();
    void saveConfigForm();
    void updateStatusLabel();
    void addClientRowToGUI(const std::string ip, int port, DeviceType deviceType);
    bool startRapsiReceivers();
    bool stopRaspiReceivers();
    void findPythonExecutable();

    //class variables
    QThread* m_screenLibTh = new QThread;
    std::string m_gConfPath = "screenLedConfig.json"; //using runtimefolder should be fine for now since if this file does not exist, it gets generated by screenCaptureWorker during its initialization
    int m_numRaspis = 1;
#if defined(WIN32)
    screenCaptureWorkerWindows* m_screenCapWorker = new screenCaptureWorkerWindows(m_gConfPath);
#else
    screenCaptureWorkerLinux* m_screenCapWorker = new screenCaptureWorkerLinux(m_gConfPath);
#endif

    bool m_libScreenledThreadIsRunning = false;
    bool m_rcvsRunning = false;
    QString m_pythonCmd = "";
    runStatus currentRunStatus = runStatus::IDLE;
    std::vector<QLineEdit*> m_extraClientIpInputs;
    std::vector<QLineEdit*> m_extraClientPortInputs;
    std::vector<QComboBox*> m_extraClientDevTypeInputs;

    ReceiverRunner *m_rcvRunner = nullptr;
    QThread *m_rcvRunnerThread = new QThread(this);
    QTimer *statusUpdatetimer;  // Timer to schedule status label updates
    Ui::ScreenLedGUI *ui;
    AdvancedSettings *m_advancedSettingsWindow = nullptr;
};
#endif // SCREENLEDGUI_H
